default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@localhost:5432/movies_app_development" } %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@localhost:5432/movies_app_test" } %>

production:
  primary: &primary_production
    <<: *default
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate